### ISSUE TITLE
Steampipe service from Docker is not reachable from host machine processes

### ISSUE THREAD

**Issue by RoxKilly** [turbot/steampipe#3017]
**Describe the bug**
When running the steampipe service from within a docker container on a mac, I am unable to each it from the host machine because the `database-listen` options do not include `0.0.0.0`

**Steampipe version (`steampipe -v`)**
v0.18.1

**To reproduce**
Here is an excerpt from my docker-compose file
```
services:
  steampipe:
    image: turbot/steampipe
    container_name: steampipe
    command: steampipe service start --database-password ${STEAMPIPE_DB_PASSWORD} --database-port ${STEAMPIPE_DB_PORT} --database-listen local --foreground --show-password
    ports:
      - "${STEAMPIPE_DB_PORT?err}:${STEAMPIPE_DB_PORT?err}"
    tty: true
    # restart: unless-stopped
    environment:
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION?err}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID?err}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY?err}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN?err}
    volumes:
      - type: bind
        source: .docker/steampipe/config
        target: /home/steampipe/.steampipe/config
      - type: bind
        source: .docker/steampipe/logs
        target: /home/steampipe/.steampipe/logs
      - type: volume
        source: steampipe_data
        target: /home/steampipe/.steampipe/db/14.2.0/data
      - type: volume
        source: steampipe_internal
        target: /home/steampipe/.steampipe/internal
      - type: volume
        source: steampipe_plugins
        target: /home/steampipe/.steampipe/plugins

```

The service starts successfully and listens on `localhost`, `127.0.0.1` and a few other IPs.  However I am unable to hit it from outside Docker because those IPs are not reachable from the host machine.  If I run the service outside docker directly on the host machine, I can reach it without problem.  As far as I can see the docs for `steampipe service` do not offer a way to specify which IPs the service should listen on.

**Expected behavior**
Similar to the postgres container, there should be a way to tell the service to listen on `0.0.0.0` so that the host machine's clients can reach steampipe service running in Docker.
