### ISSUE TITLE
Add acceptance test for connection config with options block

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#995]
test hcl, json, yml and  json

```
connection "aws" {
  plugin    = "aws"
  regions     = ["us-east-1", "us-west-2"]
  options "connection" {
    cache           = true   # true, false
    cache_ttl       = 300    # int = time in seconds
  }
}
```
```
connection:
  chaos3:
    plugin: chaos
    regions:
      - us-east-1
    options:
        connection:
           cache:   true   
           cache_ttl:  300    

      ```
